<?php


/**
 * This class defines the structure of the 'magazine' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/11/12 07:13:58
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MagazineTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MagazineTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('magazine');
		$this->setPhpName('Magazine');
		$this->setClassname('Magazine');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', true, 60, null);
		$this->addColumn('DATE_OF_PUBLICATION', 'DateOfPublication', 'TIMESTAMP', false, null, null);
		$this->addColumn('PRICE', 'Price', 'FLOAT', true, 6, null);
		$this->addColumn('BOOKSELLER_ID', 'BooksellerId', 'INTEGER', true, 11, null);
		$this->addColumn('SOLD_OUT', 'SoldOut', 'TINYINT', false, 4, 0);
		$this->addColumn('CAN_BE_REORDERED', 'CanBeReordered', 'TINYINT', false, 4, 1);
		$this->addColumn('REBATE', 'Rebate', 'FLOAT', false, 3, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // MagazineTableMap
