<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/08/13 11:00:05

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=bookseller;host=localhost',
  'username' => 'root',
  'password' => 'qlung',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
